### ISSUE TITLE
Can't ssh into the karaf container

### ISSUE THREAD

**Issue by rparree** [jboss-fuse/jboss-fuse-docker#9]
Hi,

I can't ssh into the container. (See connection attempts below).

I am able to connect to hawtio and use amq (after changing `activemq.host` to `0.0.0.0`). I am also not getting the console when starting the container with `it` 

I have tried setting   `karaf.delay.console` to `true` and `false` (in both `config.properties` and in `custom.properties`

Note i am using fuse version _6.2.0.redhat-099_ (but had the same problems with an older version)
- From outside (docker host):
  
  ```
  $ ssh -p 32920 -o PasswordAuthentication=yes -o PubkeyAuthentication=no -vv  admin@localhost
  OpenSSH_6.9p1, OpenSSL 1.0.1k-fips 8 Jan 2015
  debug1: Reading configuration data /etc/ssh/ssh_config
  debug1: /etc/ssh/ssh_config line 57: Applying options for *
  debug2: ssh_connect: needpriv 0
  debug1: Connecting to localhost [127.0.0.1] port 32920. 
  debug1: Connection established.
  debug1: identity file /home/rparree/.ssh/id_rsa type 1
  debug1: key_load_public: No such file or directory
  debug1: identity file /home/rparree/.ssh/id_rsa-cert type -1
  debug1: key_load_public: No such file or directory
  debug1: identity file /home/rparree/.ssh/id_dsa type -1
  debug1: key_load_public: No such file or directory
  debug1: identity file /home/rparree/.ssh/id_dsa-cert type -1
  debug1: key_load_public: No such file or directory
  debug1: identity file /home/rparree/.ssh/id_ecdsa type -1
  debug1: key_load_public: No such file or directory
  debug1: identity file /home/rparree/.ssh/id_ecdsa-cert type -1
  debug1: key_load_public: No such file or directory
  debug1: identity file /home/rparree/.ssh/id_ed25519 type -1
  debug1: key_load_public: No such file or directory
  debug1: identity file /home/rparree/.ssh/id_ed25519-cert type -1
  debug1: Enabling compatibility mode for protocol 2.0
  debug1: Local version string SSH-2.0-OpenSSH_6.9
  ssh_exchange_identification: read: Connection reset by peer
  ```
- From inside the docker container

```
 [jboss@5a73967f4a8b bin]$ ./client -u admin -p admin -l 4 -a 8101
 21 [main] INFO org.apache.sshd.common.util.SecurityUtils - BouncyCastle not registered, using the  default JCE provider
 162 [main] DEBUG org.apache.sshd.common.io.nio2.Nio2Connector - Creating Nio2Connector
 Logging in as admin
 164 [main] DEBUG org.apache.sshd.common.io.nio2.Nio2Connector - Connecting to /0.0.0.0:8101
 org.apache.sshd.common.RuntimeSshException: Failed to get the session.
    at  org.apache.sshd.client.future.DefaultConnectFuture.getSession(DefaultConnectFuture.java:43)
    at org.apache.karaf.client.Main.main(Main.java:250)
 Caused by: java.net.ConnectException: Connection refused
    at sun.nio.ch.UnixAsynchronousSocketChannelImpl.checkConnect(Native Method)
    at  sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishConnect(UnixAsynchronousSocketChannelIm pl.java:252)
    at  sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:198)
    at  sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.jav a:213)
    at sun.nio.ch.EPollPort$EventHandlerTask.run(EPollPort.java:293)
    at java.lang.Thread.run(Thread.java:745)

```

**Comment by rparree** [comment]
I just found out the karaf container is still in `starting` mode. That's probably the reason. Now i need to find out why it is not completing the startup.

**Comment by rparree** [comment]
I have justed tried 6.2.1.redhat-044 and it works without a problem
